### ISSUE TITLE
Support for digital signatures

### ISSUE THREAD

**Issue by thomasdc** [egelke/eid#2]
Does this library support signing content via the private key embedded on the eID after unlocking with the pincode?

**Comment by egelke** [comment]
Not really, it could easily be added but the library has the purpose to run besides the middleware.  With this lib you read the files, via the X509Store you get the correct X509Certificate2 (you can find the right one by reading the cert with this lib), once you have the right one you can use the private keys via the standard X509Certificate2 methods.
